services:
  n8n:
    container_name: n8n
    build: .
    restart: unless-stopped

    ports:
      - "${PORT}:5678"

    volumes:
      - ./volumes/data:/home/node/.n8n
      - ./volumes/local:/files

    environment:
      - N8N_HOST=${HOST}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=${WEBHOOK_URL}
      - GENERIC_TIMEZONE=${TZ}
      - TZ=${TZ}

